Add unit tests for com.google.common.hash.LittleEndianByteArray
Diffblue-benchmarks/Google-guava pull request #1
Opened 2019-07-04 14:51 UTC by Braavos96

I've analysed your codebase and noticed that `com.google.common.hash.LittleEndianByteArray` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

2019-07-04 15:57 UTC, freddytuxworth requested changes

2019-07-04 15:57 UTC, freddytuxworth commented on guava-tests/test/com/google/common/hash/LittleEndianByteArrayTest.java
> +        Assert.assertTrue(LittleEndianByteArray.usingUnsafe());
Not sure about this test

2019-07-08 12:46 UTC, Braavos96 commented on guava-tests/test/com/google/common/hash/LittleEndianByteArrayTest.java
> +        Assert.assertTrue(LittleEndianByteArray.usingUnsafe());
I have removed this test

2019-07-10 09:42 UTC, paulkennethkent commented on guava-tests/test/com/google/common/hash/LittleEndianByteArrayTest.java
> +                new byte[]{1, 2, 3, 4, 5, 6, 7, 8}, 0, 1L);
Don't you normally put a gap here?

2019-07-10 09:46 UTC, Braavos96 commented on guava-tests/test/com/google/common/hash/LittleEndianByteArrayTest.java
> +                new byte[]{1, 2, 3, 4, 5, 6, 7, 8}, 0, 1L);
Done

2019-07-10 10:53 UTC, paulkennethkent approved these changes

2019-07-10 15:26 UTC, JohnLBergqvist approved these changes

2019-07-11 08:52 UTC, closed without merging